### PR TITLE
feat: support custom key mapping

### PR DESCRIPTION
**Pull request by eeeXun**

### CODE REVIEW

**Comment by doums** [comment]
Hey, so I checked a bit the PR, first thx for it.
As my 2 cents feedback, I'd say it's not ideal as it only allows keys to combine with arbitrary `Ctrl` modifier. Which is a bit restrictive and I think will be a bit confusing for the user. Usually when user provide their keymap, they expect to provide full combination (key + modifier) as they wish.
But as you said you made this way because of avoiding conflict with default TUI framework bindings, maybe for some other reason?

In any case I think this should appear clearly in the README, like "Only keybinding with `Ctrl` modifier are supported. Please only provide the key for each custom keybind (`Ctrl` is always assumed)"

**Comment by eeeXun** [comment]
Thanks for the feedback.

>But as you said you made this way because of avoiding conflict with default TUI framework bindings, maybe for some other reason?

After looking into it. I found it's not conflict. It can be overwritten. Currently, it only provide key with modifier `Ctrl` and function key from `F1` to `F64`.

> I'd say it's not ideal as it only allows keys to combine with arbitrary Ctrl modifier.

Yes, you are right. This is not an idea design. But other modifier, like `Alt`, is a bit  cumbersome to handle. I look the [lf](https://github.com/gokcehan/lf), which use the same TUI framework, do the job. I might look into how it is designed.

**Comment by eeeXun** [comment]
In the last commit

>For key to combine with `Ctrl`, the value can be `"C-space"`, `"C-\\"`, `"C-]"`, `"C-^"`, `"C-_"` or `"C-a"` to `"C-z"`.
>
>⚠️ Note, don't use `"C-c"`, `<C-c>` is for exit program.
>
>For key to combine with `Alt`, the value can be `"A-space"` or `"A-"` + the character you want.
>
>Or you can use function key, the value can be `"F1"` to `"F64"`.

I think this can cover all cases. If the document or the feature is not completed, feedback is still welcome.

**Comment by eeeXun** [comment]
UPDATE:
You can set `"C-c"` now. And you can config the `exit` key.

**Comment by doums** [comment]
Looks good now

**Pull request merged**
