### PR TITLE
feat: copy text

### PR DESCRIPTION
**Pull request by eeeXun**
Linux need `xclip`.
macOS need `pbcopy`.

I'm not using macOS. Test wanted.

### CODE REVIEW

**Comment by aslak01** [comment]
Not working on macOS, and I think probably just due to using Alt, which is bound to a third layer of characters on macOS. Alt-c produces ç, so it's probably a better idea to use Ctrl for copy for compatibility. Also, if possible copying without having to highlight first would be preferable in my opinion. If I'd need a subset of the text, I'd prefer to do that wherever I'm editing text.

**Comment by eeeXun** [comment]
> Not working on macOS, and I think probably just due to using Alt, which is bound to a third layer of characters on macOS. Alt-c produces ç, so it's probably a better idea to use Ctrl for copy for compatibility. Also, if possible copying without having to highlight first would be preferable in my opinion. If I'd need a subset of the text, I'd prefer to do that wherever I'm editing text.

That's disappointing. Many `Ctrl` bindings are already occupied by TUI framework.
What about `<A-s>` for copy selected text? `<A-a>` for copy all text without selected?

**Comment by aslak01** [comment]
`<A-s>` produces `ß` and `<A-a>` ``. In general it's not possible to use Alt bindings while supporting macOS in the terminal without actually mapping those commands to those characters, which is also impossible to generalise since they are different depending on the keyboard language settings. I would suggest something like `<C-y>` as in yank, or something or some other workaround binding, potentially in addition to the Alt bindings, for macOS support.

Edit: as a note, personally I'd love full on vim bindings for this, similar to something like lazygit.

**Comment by eeeXun** [comment]
> <A-s> produces ß and <A-a> . In general it's not possible to use Alt bindings while supporting macOS in the terminal without actually mapping those commands to those characters, which is also impossible to generalise since they are different depending on the keyboard language settings. I would suggest something like <C-y> as in yank, or something or some other workaround binding, potentially in addition to the Alt bindings, for macOS support.

Oh, I get it. I will not consider using Alt bindings.
I think `<C-y>` to copy selected. `<C-g>` to copy left window text. `<C-r>` to copy right window text. How do you think?

> Edit: as a note, personally I'd love full on vim bindings for this, similar to something like lazygit.

I don't think this is possible due to TUI framework [tview](https://github.com/rivo/tview). It's normal editor, not a vim editor.

**Comment by aslak01** [comment]
Yes, that would work, `<C-r>` is quite useable. It would also be great if the key binds could be modified with a file in `.conf` (please not in `~`), as my use case for this has some rather eccentric bindings going on already, and I might want to modify them to suit it better.

**Comment by eeeXun** [comment]
> It would also be great if the key binds could be modified

Okay, I'll do this later. I'll add a dropdown list instead of letting user modify it.

> a file in .conf (please not in ~), as my use case for this has some rather eccentric bindings going on already, and I might want to modify them to suit it better.

GTT already have a config file. As mentioned there https://github.com/eeeXun/GTT/issues/2#issuecomment-1290339657.

**Comment by aslak01** [comment]
@eeeXun That's great, are the config options specified anywhere?

**Comment by eeeXun** [comment]
No. As I mentioned. Many key are already occupied by TUI framework.
Like `<C-a>` for first char of line, `<C-w>` for delete word, etc.
So there won't be many options.

**Pull request merged**
